export enum actionTypes {
  FETCH_PEOPLE_REQUEST = 'FETCH_PEOPLE_REQUEST',
  FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS',
  FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE',
  SET_CONNECTION_INFO = 'SET_CONNECTION_INFO',
}
